### ISSUE TITLE
Mutiple Public Keys

### ISSUE THREAD

**Issue by serravin** [antonscheffer/as_crypto#1]
Hello Anton

I need to encrypt a file that three other systems need to decrypt. For this I have received a public key from each system. Can I also use the function "pkEncrypt" for this, or is this only meant for a single public key?

Thanks & greetings
Vincenzo

**Comment by antonscheffer** [comment]
Public and private keys come in pairs. That means that one public key belongs to only one private key. Every system has is own pair. So you need to encrypt your message 3 times.
