### ISSUE TITLE
Construct RSA Public Key from JSON Web Key modulus "n" and exponent "e"?

### ISSUE THREAD

**Issue by u797595** [antonscheffer/as_crypto#3]
Can AS_CRYPTO be used to construct an RSA Public Key from a JSON Wek Key [modulus ( "n" ), exponent ("e")?

Example JWK:
{
  "kty": "RSA",
  "use": "sig",
  "kid": "Mr5-AUibfBii7Nd1jBebaxboXW0",
  "x5t": "Mr5-AUibfBii7Nd1jBebaxboXW0",
  "n": "yr3v1uETrFfT17zvOiy01w8nO-1t67cmiZLZxq2ISDdte9dw-IxCR7lPV2wezczIRgcWmYgFnsk2j6m10H4tKzcqZM0JJ_NigY29pFimxlL7_qXMB1PorFJdlAKvp5SgjSTwLrXjkr1AqWwbpzG2yZUNN3GE8GvmTeo4yweQbNCd-yO_Zpozx0J34wHBEMuaw-ZfCUk7mdKKsg-EcE4Zv0Xgl9wP2MpKPx0V8gLazxe6UQ9ShzNuruSOncpLYJN_oQ4aKf5ptOp1rsfDY2IK9frtmRTKOdQ-MEmSdjGL_88IQcvCs7jqVz53XKoXRlXB8tMIGOcg-ICer6yxe2itIQ",
  "e": "AQAB",
  "x5c": [
    "MIIDBTCCAe2gAwIBAgIQff8yrFO3CINPHUTT76tUsTANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTIxMTAyNDE3NDU1NloXDTI2MTAyNDE3NDU1NlowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMq979bhE6xX09e87zostNcPJzvtbeu3JomS2catiEg3bXvXcPiMQke5T1dsHs3MyEYHFpmIBZ7JNo+ptdB+LSs3KmTNCSfzYoGNvaRYpsZS+/6lzAdT6KxSXZQCr6eUoI0k8C6145K9QKlsG6cxtsmVDTdxhPBr5k3qOMsHkGzQnfsjv2aaM8dCd+MBwRDLmsPmXwlJO5nSirIPhHBOGb9F4JfcD9jKSj8dFfIC2s8XulEPUoczbq7kjp3KS2CTf6EOGin+abTqda7Hw2NiCvX67ZkUyjnUPjBJknYxi//PCEHLwrO46lc+d1yqF0ZVwfLTCBjnIPiAnq+ssXtorSECAwEAAaMhMB8wHQYDVR0OBBYEFDiZG6s5d9RvorpqbVdS2/MD8ZKhMA0GCSqGSIb3DQEBCwUAA4IBAQAQAPuqqKj2AgfC9ayx+qUu0vjzKYdZ6T+3ssJDOGwB1cLMXMTUVgFwj8bsX1ahDUJdzKpWtNj7bno+Ug85IyU7k89U0Ygr55zWU5h4wnnRrCu9QKvudUPnbiXoVuHPwcK8w1fdXZQB5Qq/kKzhNGY57cG1bwj3R/aIdCp+BjgFppOKjJpK7FKS8G2v70eIiCLMapK9lLEeQOxIvzctTsXy9EZ7wtaIiYky4ZSituphToJUkakHaQ6evbn82lTg6WZz1tmSmYnPqRdAff7aiQ1Sw9HpuzlZY/piTVqvd6AfKZqyxu/FhENE0Odv/0hlHzI15jKQWL1Ljc0Nm3y1skut"
  ],
  "issuer": "https://login.microsoftonline.com/{tenantid}/v2.0"
}

Desired public key (raw(2048) datatype) 
-- utl_i18n.string_to_raw( data => pubkey, dst_charset => 'AL32UTF8'  );
-- PEM format?
pubkey    VARCHAR (2000) := 
    'MIIBCgKCAQEA5NxSHpPK04omQwtdPX4Sz5crFsU/30gddy8UM0GtmXfBXuqgoHsW'
  ||'K340dwaDlFPxHbijdwDyjbZRBJ5EmtoP2FirmLKMpXzaF4jOEGlzAo7D1sXDQ2xH'
  ||'lAfw9xrpIDLXs9FfcKRpKF/o04bQIIgkt9qKueQcjLWXg5ww/VA5oINx3khKcfC3'
  ||'vYsVuPLeqDNkrT7n0m/ysTGdIsZ0XVk6qdFAAxqnPeXRuUOch3ut9bvfgGdSSLDP'
  ||'7mzgo+kELX64CyOccd4NN6mskt4wn+wo4DQfYpIb5LPKCq93ZDzNqmSD72BGLiwm'
  ||'yO7jSNHwbbfZT6HzvNwoV/WXFdflap/4MwIDAQAB

**Comment by u797595** [comment]
With OpenSSL 
https://medium.com/@bn121rajesh/understanding-rsa-public-key-70d900b1033c#:~:text=Public%20key%20contains%20modulus%20and,to%20decode%20the%20original%20value.

**Comment by u797595** [comment]
https://cryptobook.nakov.com/asymmetric-key-ciphers/the-rsa-cryptosystem-concepts
"The same RSA public key, encoded in the traditional for RSA format PKCS#8 PEM ASN.1 looks like this:"
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApwni+ErA4h6wyqAYz39p
f3dOlvgRX8I1npz2Cx3Y1ASNl0zfhCK+9r48FisEuRb36iEz8OPk4O7hZIWb2cHg
7wNXwUL09jO0rdSquGyPiJXNM/v04CTZo61r5iZ1cLSnLSw0NU4BOedK2mZaFqJh
FJDeu44TGmz/x+8l50JAgD3XGk/NlTyYgRGwqpu8TFcCT8XoxEYq2QScfxq+2FnG
NFX6bVi1zDSj0yBv90uelsM226zwzdGO0MZnls4AqwfzayTL4zQlI/2CFajnf4no
agjbkR8jdFk4je5kLa58smRKA+ce1cb6UHfPQJD6+lVgSLU2uHmoj2KGmPDHtCDE
twIDAQAB
-----END PUBLIC KEY-----

**Comment by antonscheffer** [comment]
No, that is not possible. And I have no plans for implementing that.
Or do you want to use a JWK as the public key in the verify function?

**Comment by u797595** [comment]
The later.  

Basically, the opposite of the function as_crypto.parse_DER_RSA_PUB_key(  p_key raw, p_key_parameters out tp_key_parameter   ) return boolean

construct_DER_RSA_PUB_key( p_key_parameters IN tp_key_parameter, p_key OUT raw ) boolean

where p_key_parameters have "n" and "e" from the JWK. ( "n" and "e" are Base64URLUInt in the JWK)

**Comment by antonscheffer** [comment]
No, in that case it makes more sense (to me at last) to extend the public key parser to extract the n and e values from a JWK. But even that is not very high on my to do list.

**Comment by u797595** [comment]
What?  I am sorry, I don't think I can be clear enough for us to understand each other.

n and e values can easily be extracted from the JWK.  They are base64URL encoded unsigned integers in the JSON. One doesn't need a public key parser to do that. ( see prior JWK example )

What I am looking for is a way to construct the RSA public key in the binary DER format to pass to the function dbms_crypto.verify( ... ) from the n and e integers.

The as_crypto.parse_DER_RSA_PUB_key is doing the reverse.  It is taking an RSA public key in DER format and extracting/parsing out the n and e integers of the public key.

You have answered my question.  
AS_CRYPTO doesn't have functions/procedures to do this.  I don't expect you to implement this in AS_CRYPTO.

**Comment by antonscheffer** [comment]
Just saying that it makes much more sense to extend the public key parse used in as_crypto.verify, so use only use as_crypto.verify , than to create a new function in as_crypto, and use that new function in as_crypto as input for dbms_crypto.verify :)
